mail_systems:

  - software:           "Google Workspace"
    vendor:             "Google LLC"
    provider_category:  big_tech

    roles:
      - role:   smtp_out
        rating: 2
        detection:
          hostname:
            - ".*\\.smtp\\.google\\.com$"
            - ".*\\.googlemail\\.com$"
          banner:
            - "(?i).*Google.*ESMTP.*"

      - role:   smtp_in
        rating: 2
        detection:
          hostname:
            - "aspmx\\.l\\.google\\.com$"
            - "alt[1-4]\\.aspmx\\.l\\.google\\.com$"
            - ".*\\.googlemail\\.com$"
          banner:
            - "(?i).*Google.*ESMTP.*"

      - role:   webmailer
        rating: 2
        detection:
          hostname:
            - "^mail\\.google\\.com$"
          banner: []

  - software:           "Microsoft 365"
    vendor:             "Microsoft Corporation"
    provider_category:  big_tech

    roles:
      - role:   smtp_out
        rating: 2
        detection:
          hostname:
            - ".*\\.outbound\\.protection\\.outlook\\.com$"
            - ".*\\.smtp\\.microsoft\\.com$"
          banner:
            - "(?i).*Microsoft.*ESMTP.*"
            - "(?i).*outlook\\.com.*"

      - role:   smtp_in
        rating: 2
        detection:
          hostname:
            - ".*\\.mail\\.protection\\.outlook\\.com$"
          banner:
            - "(?i).*Microsoft.*ESMTP.*"

      - role:   webmailer
        rating: 2
        detection:
          hostname:
            - "^outlook\\.office365\\.com$"
            - "^outlook\\.office\\.com$"
          banner: []

ip_ratings:

  - asn_org_pattern:  "(?i).*AMAZON.*"
    rating: 3
    org: "AWS"

  - asn_org_pattern:  "(?i).*GOOGLE.*"
    rating: 2
    org: "Google Cloud / GCP"

  - asn_org_pattern:  "(?i).*MICROSOFT.*"
    rating: 2
    org: "Azure"